# Generated by Django 5.2.6 on 2025-11-01 07:55

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_technology_alter_homepage_options_homepage_about_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "project_name",
                    models.CharField(
                        help_text="e.g., Django, React, etc.", max_length=200
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Brief description of your contribution",
                        max_length=300,
                    ),
                ),
                (
                    "description",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Detailed explanation of what you contributed",
                    ),
                ),
                ("pr_url", models.URLField(verbose_name="Pull Request URL")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("merged", "Merged ✅"),
                            ("open", "Open"),
                            ("closed", "Closed"),
                        ],
                        default="merged",
                        max_length=20,
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        blank=True, help_text="Date merged/submitted", null=True
                    ),
                ),
                (
                    "lines_changed",
                    models.CharField(
                        blank=True, help_text="e.g., +100 -50", max_length=50
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributions",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
                "abstract": False,
            },
        ),
    ]
