# Generated by Django 5.2.6 on 2025-11-01 08:12

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_contribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("reading", "📖 Currently Reading"),
                            ("completed", "✅ Completed"),
                            ("planned", "📚 Want to Read"),
                        ],
                        default="reading",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("finish_date", models.DateField(blank=True, null=True)),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "1 ⭐"),
                            (2, "2 ⭐"),
                            (3, "3 ⭐"),
                            (4, "4 ⭐"),
                            (5, "5 ⭐"),
                        ],
                        help_text="Rate out of 5 stars",
                        null=True,
                    ),
                ),
                (
                    "key_takeaways",
                    wagtail.fields.RichTextField(
                        blank=True, help_text="What you learned from this book"
                    ),
                ),
                (
                    "book_url",
                    models.URLField(
                        blank=True, help_text="Link to Goodreads, Amazon, etc."
                    ),
                ),
                (
                    "page",
                    modelcluster.fields.ParentalKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="home.homepage",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
    ]
