# Generated by Django 5.2.6 on 2025-11-01 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Your public email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="github_url",
            field=models.URLField(blank=True, help_text="Your GitHub profile URL"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="linkedin_url",
            field=models.URLField(blank=True, help_text="Your LinkedIn profile URL"),
        ),
        migrations.AddField(
            model_name="homepage",
            name="twitter_url",
            field=models.URLField(blank=True, help_text="Your Twitter/X profile URL"),
        ),
    ]
